{ self }:
{ config, lib, pkgs, ... }:

let
  cfg = config.services.mneme;

  # NPU support requires the -gpu variant; the plain image is CPU-only.
  ovmsImage = "openvino/model_server:2026.0-gpu";

  # Lightweight base for the export oneshot — no Ubuntu cruft, just
  # python + pip-installed optimum.
  pythonImage = "python:3.12-slim";

  # In-container Python that does the actual export+reshape+tokenizer
  # conversion. Lives in the Nix store, mounted read-only into the pull
  # container at /pull.py.
  pullPyScript = pkgs.writeText "mneme-ovms-pull.py" ''
    """
    mneme: build a static-shape OVMS embeddings model.

    Steps:
      1. optimum-cli export <MODEL> → /staging (FP/INT8 IR with dynamic shapes).
      2. core.read_model + reshape({inputs: [1, SEQ_LEN]}) → static IR.
      3. Save static IR to /models/embeddings/openvino_model.{xml,bin}.
      4. Convert HF tokenizer → openvino_tokenizer.{xml,bin} + detokenizer.
      5. Write /models/embeddings/graph.pbtxt (Mediapipe EmbeddingsCalculatorOV).
      6. Write /models/config.json referencing the graph.

    All paths are container-internal. /models is the bind-mount.
    """
    import json
    import os
    import shutil
    import subprocess
    from pathlib import Path

    MODEL = os.environ["MNEME_MODEL"]
    SEQ_LEN = int(os.environ["MNEME_SEQ_LEN"])
    POOLING = os.environ["MNEME_POOLING"]
    DEVICE = os.environ["MNEME_DEVICE"]

    MODELS = Path("/models")
    STAGING = MODELS / ".staging"
    EMB = MODELS / "embeddings"

    if STAGING.exists():
        shutil.rmtree(STAGING)
    if EMB.exists():
        shutil.rmtree(EMB)
    EMB.mkdir(parents=True)

    print(f"[1/6] Exporting {MODEL} via optimum-cli (INT8) → {STAGING}")
    subprocess.check_call([
        "optimum-cli", "export", "openvino",
        "--model", MODEL,
        "--task", "feature-extraction",
        "--weight-format", "int8",
        "--library", "transformers",
        "--trust-remote-code",
        str(STAGING),
    ])

    import openvino as ov
    core = ov.Core()
    print(f"[2/6] Reading IR + reshaping inputs to [1, {SEQ_LEN}]")
    model = core.read_model(str(STAGING / "openvino_model.xml"))
    model.reshape({p.get_any_name(): [1, SEQ_LEN] for p in model.inputs})

    print(f"[3/6] Saving static IR → {EMB}/openvino_model.xml")
    ov.save_model(model, str(EMB / "openvino_model.xml"), compress_to_fp16=False)

    print("[4/6] Converting HF tokenizer → OpenVINO tokenizer + detokenizer")
    from openvino_tokenizers import convert_tokenizer
    from transformers import AutoTokenizer
    hf_tok = AutoTokenizer.from_pretrained(MODEL, trust_remote_code=True)
    ov_tok, ov_detok = convert_tokenizer(hf_tok, with_detokenizer=True)
    ov.save_model(ov_tok,   str(EMB / "openvino_tokenizer.xml"))
    ov.save_model(ov_detok, str(EMB / "openvino_detokenizer.xml"))

    print("[5/6] Writing graph.pbtxt (EmbeddingsCalculatorOV, target_device="
          f"{DEVICE}, pooling={POOLING})")
    graph_pbtxt = (
        "# Generated by mneme-ovms-pull\n"
        f"# model={MODEL} seq_len={SEQ_LEN} pooling={POOLING} device={DEVICE}\n"
        "input_stream: \"REQUEST_PAYLOAD:input\"\n"
        "output_stream: \"RESPONSE_PAYLOAD:output\"\n"
        "node {\n"
        f"    name: \"{MODEL}\",\n"
        "    calculator: \"EmbeddingsCalculatorOV\"\n"
        "    input_side_packet: \"EMBEDDINGS_NODE_RESOURCES:embeddings_servable\"\n"
        "    input_stream: \"REQUEST_PAYLOAD:input\"\n"
        "    output_stream: \"RESPONSE_PAYLOAD:output\"\n"
        "    node_options: {\n"
        "        [type.googleapis.com / mediapipe.EmbeddingsCalculatorOVOptions]: {\n"
        "            models_path: \"./\",\n"
        "            normalize_embeddings: true,\n"
        "            truncate: false,\n"
        f"            pooling: {POOLING},\n"
        f"            target_device: \"{DEVICE}\",\n"
        "            plugin_config: '{\"NUM_STREAMS\":\"1\"}',\n"
        "        }\n"
        "    }\n"
        "}\n"
    )
    (EMB / "graph.pbtxt").write_text(graph_pbtxt)

    print("[6/6] Writing /models/config.json")
    config = {
        "model_config_list": [],
        "mediapipe_config_list": [
            {"name": "embeddings", "graph_path": "/models/embeddings/graph.pbtxt"}
        ],
    }
    (MODELS / "config.json").write_text(json.dumps(config, indent=2))

    shutil.rmtree(STAGING, ignore_errors=True)
    print("Done.")
  '';

  # Wrapper that orchestrates the export container. Idempotent — the
  # stamp file encodes (model, seq_len, pooling, device); when any
  # changes, the embeddings dir is rebuilt from scratch.
  pullScript = pkgs.writeShellApplication {
    name = "mneme-ovms-pull";
    runtimeInputs = [ pkgs.podman pkgs.coreutils ];
    text = ''
      set -euo pipefail
      MODELS_DIR="${cfg.stateDir}/ovms-models"
      STAMP_FILE="$MODELS_DIR/.mneme-stamp"
      STAMP="model=${cfg.embeddingModel} seq=${toString cfg.embeddingMaxSeqLen} pool=${cfg.embeddingPooling} dev=${cfg.embeddingDevice}"

      mkdir -p "$MODELS_DIR"

      if [ -f "$MODELS_DIR/config.json" ] \
         && [ -f "$MODELS_DIR/embeddings/openvino_model.xml" ] \
         && [ -f "$STAMP_FILE" ] \
         && [ "$(cat "$STAMP_FILE")" = "$STAMP" ]; then
        echo "[mneme-ovms-pull] config matches stamp, skipping rebuild."
        echo "  $STAMP"
        exit 0
      fi

      echo "[mneme-ovms-pull] Building embedding model:"
      echo "  $STAMP"

      ${pkgs.podman}/bin/podman run --rm \
        --user=0:0 \
        --workdir /tmp \
        -v "$MODELS_DIR":/models:rw \
        -v ${pullPyScript}:/pull.py:ro \
        -e MNEME_MODEL="${cfg.embeddingModel}" \
        -e MNEME_SEQ_LEN="${toString cfg.embeddingMaxSeqLen}" \
        -e MNEME_POOLING="${cfg.embeddingPooling}" \
        -e MNEME_DEVICE="${cfg.embeddingDevice}" \
        -e PIP_DISABLE_PIP_VERSION_CHECK=1 \
        ${pythonImage} \
        bash -c '
          set -e
          echo "Installing optimum[openvino] + openvino-tokenizers ..."
          pip install --quiet --no-warn-script-location \
            "optimum[openvino]>=1.20" "openvino-tokenizers" "transformers"
          python3 /pull.py
        '

      echo "$STAMP" > "$STAMP_FILE"
      echo "[mneme-ovms-pull] Done."
    '';
  };
in
{
  config = lib.mkIf cfg.enable {
    virtualisation.podman.enable = lib.mkDefault true;

    # Pull oneshot: builds the static-shape model + tokenizer + graph at
    # first run (and again whenever the model/seq_len/pooling/device options
    # change). Decoupled from OVMS — runs once, OVMS then serves.
    systemd.services."mneme-ovms-pull" = {
      description = "mneme: build static-shape embedding model for OVMS";
      wantedBy = [ "podman-mneme-ovms.service" ];
      before = [ "podman-mneme-ovms.service" ];
      wants = [ "network-online.target" ];
      after = [ "network-online.target" ];
      serviceConfig = {
        Type = "oneshot";
        # Root: needs to drive rootful podman + write to the bind-mounted
        # models dir.
        User = "root";
        ExecStart = "${pullScript}/bin/mneme-ovms-pull";
        RemainAfterExit = true;
        TimeoutStartSec = "30min";
      };
    };

    # OVMS serves the prebuilt static-shape model. Nothing here changed —
    # we still bind /dev/accel/accel0 with the host's render/video GIDs so
    # the in-container OpenVINO can reach the NPU.
    virtualisation.oci-containers.containers."mneme-ovms" = {
      image = ovmsImage;
      autoStart = true;
      ports = [ "127.0.0.1:${toString cfg.ports.openvino}:8000" ];
      volumes = [
        "${cfg.stateDir}/ovms-models:/models:ro"
      ];
      cmd = [
        "--rest_port" "8000"
        "--config_path" "/models/config.json"
      ];
      extraOptions = [
        "--user=0:0"
        "--device=/dev/accel/accel0"
        "--group-add=${toString config.users.groups.render.gid}"
        "--group-add=${toString config.users.groups.video.gid}"
      ];
    };
  };
}
